---
- name: Configure geoipupdate
  template:
    src: 'GeoIP.conf.j2'
    dest: '{{ maxmind_filename }}'
    owner: root
    group: root
    mode: 0640
  notify: Update GeoIP databases

#- name: Install Cron task for autoupdates

